package templates

var AppxModel = `// AUTO GENERATED BY appx-cli - DO NOT EDIT

package {{.Pkg}}

import (
	"appengine/datastore"
	"github.com/drborges/appx"
)

type {{.Name}}AppxModel struct {
	{{.Name}}
	db *appx.Datastore
}

func (model *{{.Name}}AppxModel) Save() error {
	return model.db.Save(model)
}

func (model *{{.Name}}AppxModel) Delete() error {
	return model.db.Delete(model)
}`
