// AUTO GENERATED BY appx-cli - DO NOT EDIT

package models

import (
	
	"github.com/drborges/appx"
)

type User struct {
	appx.Model
	
	Age int
	
	Email string
	
	Name string
	
	Token string
	
}

func (user *User) KeySpec() *appx.KeySpec {
	return &appx.KeySpec{
		Kind: "users",
		
		Incomplete: true,
		
		
		
		
	}
}



